# Generated by Django 5.0.6 on 2024-06-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydroponicsystem',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
