# Generated by Django 5.0.6 on 2024-06-02 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems_api', '0002_alter_hydroponicsystem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydroponicsystem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hydroponicsystemmeasurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
